---
- name: Dotfiles
  hosts: localhost
  roles:
    - emacs
    - neovim
    - vim

  tasks:
    - name: Ensure $HOME/.config
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config'
        state: directory
        mode: '755'

    - name: Link dotfiles
      ansible.builtin.file:
        dest: '{{ ansible_env.HOME }}/.config/{{ item }}'
        src: '{{ playbook_dir }}/config/{{ item }}'
        state: link
      with_lines: ls -1 {{ playbook_dir }}/config

    - name: Ensure block in file at home
      ansible.builtin.blockinfile:
        path: '{{ ansible_env.HOME }}/.{{ item }}'
        create: true
        mode: '644'
        block: '{{ lookup("file", "{{ playbook_dir }}/home/{{ item }}") }}'
      with_lines: ls -1 {{ playbook_dir }}/home

    - name: Use vim9script
      ansible.builtin.lineinfile:
        path: '{{ ansible_env.HOME }}/.{{ item }}'
        insertbefore: BOF
        line: vim9script
      loop:
        - gvimrc
        - vimrc
