---
version: '3'

tasks:
  default:
    platforms:
      - windows
    cmds:
      - for:
        - localappdata
        - appdata
        - emacs
        task: '{{.ITEM}}'

  localappdata:
    vars:
      APPS:
        Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState
        nvim
    cmds:
      - for:
          var: APPS
        cmd: >-
          CMD /C
          IF NOT EXIST '{{joinPath .LOCALAPPDATA .ITEM}}'
          MKLINK /J    '{{joinPath .LOCALAPPDATA .ITEM}}' '{{joinPath .TASKFILE_DIR "userprofile" "AppData" "Local" .ITEM}}'

  appdata:
    vars:
      APPS:
        Code
    cmds:
      - for:
          var: APPS
        cmd: >-
          CMD /C
          IF NOT EXIST '{{joinPath .APPDATA .ITEM}}'
          MKLINK /J    '{{joinPath .APPDATA .ITEM}}' '{{joinPath .TASKFILE_DIR "userprofile" "AppData" "Roaming" .ITEM}}'
  emacs:
    cmds:
      - cmd: >-
          CMD /C
          IF NOT EXIST '{{joinPath .APPDATA ".emacs.d"}}'
          MKLINK /J    '{{joinPath .APPDATA ".emacs.d"}}' '{{joinPath .TASKFILE_DIR "config" "emacs"}}'
