[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-unimpaired'

[[plugins]]
repo = 'vim-airline/vim-airline'
